# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "elenzil.github.io/orionreads"
title = "Orion Reads"
copyright = ""
canonifyURLs = true
paginate = 37
theme = "hugo-clarity"

DefaultContentLanguage = "en"

[taxonomies]
author = "authors"
book = "books"
year = "years"
stores = "stores"
things = "things"

[outputs]
home = ["HTML", "RSS", "JSON"]

